# Generated by Django 4.2.5 on 2023-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_achievement_alter_employee_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='availability',
            field=models.CharField(blank=True, choices=[('Ready to interview', 'Ready to interview'), ('Open to offers', 'Open to offers'), ('Closed to offers', 'Closed to offers')], max_length=50),
        ),
    ]
