# Generated by Django 4.2.5 on 2023-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_job_job_type_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
